In [2]:
import pandas as pd

#정수형 series

s=pd.Series([1,2,3,4,8])
print(s)

0    1
1    2
2    3
3    4
4    8
dtype: int64


In [3]:
# 실수형 Series

s=pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [4]:
#실수형 Series
s=pd.Series([1,2.5,3,8.9,7])

print(s)


0    1.0
1    2.5
2    3.0
3    8.9
4    7.0
dtype: float64


In [6]:
# 인덱스 지정
s=pd.Series([1,2.5,3,8.9,7], index=['a','b','c','d','e'])
print(s)


a    1.0
b    2.5
c    3.0
d    8.9
e    7.0
dtype: float64


In [12]:
import numpy as np

a=np.array([1,2,3])
print(a)

b=np.zeros(5)
print(b)

c=np.ones((2,3)) #차원으로 입력시 괄호안에 차원 demension을 다시 또 다른 괄호안해 묶어서 기입
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a, b))
# 요소별 곱
print(np.multiply(a, b))
# 어레이값의 평균
print(np.mean(b))

[5 5 5 5]
[4 6 6 4]
2.5


In [14]:
# 0과 1사이에서 균일한 분포를 갖는 숫자 샘플링
a = np.random.rand(2,5)
print(a)
# 표준정규분포를 갖는 숫자들 샘플링
b = np.random.randn(2,4)
print(b)

[[0.95178287 0.44321723 0.36356272 0.63254805 0.97217959]
 [0.61680644 0.81655162 0.55350572 0.68657053 0.33555429]]
[[ 0.15708781 -1.09101702 -0.86360354 -0.747394  ]
 [-1.84509013 -1.70874797  2.21340997  2.43394806]]


In [15]:
# 파이
a = np.pi
print(a)
# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [16]:
a = np.array([1.2,5,6,8])
print(type(a))
print(a)
# 어레이 요소의 자료형을 알고싶을때
print(a.dtype)

<class 'numpy.ndarray'>
[1.2 5.  6.  8. ]
float64


In [17]:
a = np.array([(1,2,3,4),(1,2,3,4)])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [18]:
# 타입 지정
a = np.array(([1,2,3],[4,5,6]),dtype = complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [19]:
print(np.zeros(10))
b = np.ones((2,3,4), dtype = np.int16)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [20]:
no = [1,2,3]
subjname = []
subjname.append('수학')
subjname.append('과학')
subjname.append('파이썬')
subject = pd.DataFrame()
subject['과목번호'] = no
subject['과목명'] = subjname
print(subject)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


In [26]:
subject.to_excel("C:\pythonproject\subject.xlsx", index=False) #index=Fasle로 하면 불러온 data에 자동으로 추가된 Index가 없이 저장해준다.


In [29]:
subject.to_csv("C:\pythonproject\subject.csv", encoding='utf-8-sig',index=True)

In [30]:
# 데이터 프레임은 파이썬의 리스트와 딕셔너리의 조합이다.
df = pd.DataFrame({"이름":["홍길동", "홍길순", "임꺽정"],"age":[20,50,32], "성별":["male", "female", "male"]})
print(df)
# 데이터 프레임에서 성별컬럼만 출력
print(df["성별"])
# 데이터프레임에 고향컬럼 추가
home = pd.Series(["서울", "부산", "대전"], name = "고향")
df["고향"] = home
# 집계함수
# 평균, 최대값, 최솟값
print(df["age"].mean())
print(df["age"].max())
print(df["age"].min())

    이름  age      성별
0  홍길동   20    male
1  홍길순   50  female
2  임꺽정   32    male
0      male
1    female
2      male
Name: 성별, dtype: object
34.0
50
20


In [36]:
df = pd.DataFrame({"이름":["홍길동", "홍길순", "임꺽정"],"age":[20,50,32], "성별":["male", "female", "male"]})
# 데이터 프레임의 기본 통계 내용을 출력
print(df.describe())
# head는 위에서부터 데이터를 끊어온다
print(df.head(2))
# tail은 밑에서부터 데이터를 끊어온다.
print(df.tail(2))


             age
count   3.000000
mean   34.000000
std    15.099669
min    20.000000
25%    26.000000
50%    32.000000
75%    41.000000
max    50.000000
    이름  age      성별
0  홍길동   20    male
1  홍길순   50  female
    이름  age      성별
1  홍길순   50  female
2  임꺽정   32    male


In [75]:
df = pd.read_excel("order.xlsx")
print(df)
# 1. 손흥민의 주문 개수는?
#is_son = df["name"] == "손흥민"
#print(is_son)
#print(df[is_son]["order_no"].count())
#print(df[df["name"] == "손흥민"]['order_no'].count())

# 2. 손흥민이 산 상품은?
#print(df[df['name']=='손흥민']['product'])

# 3. 스커트를 산 사람은?
#print(df[df['product']=='스커트']['name'])

# 4. 가장 많이 주문한 사람의 아이디와 이름, 주문횟수는?
#newdf = df.groupby(["user_id","name"])["order_no"].get_group(('user1','손흥민'))
#newdf = df.groupby(["user_id","name"])["order_no"].count().reset_index(name = "count")
newdf = df.groupby(["user_id","name"])["order_no"].count().reset_index(name = "count")


# 기본 정렬 방식은 오름차순, 내림차순으로 정렬하고 싶을 경우 ascending = False
newdf = newdf.sort_values("count", ascending = False)
#newdf=newdf.sort_values('count',ascending=False)
print(newdf)
# 5. 김지원이 사용한 총 금액은?
is_kim = df["name"] == "김지원"
print(df[is_kim]["price"].sum())

   Unnamed: 0  order_no user_id user_pass name address product    price  brand
0           0         1   user1     pass1  손흥민      런던     운동화   100000    나이키
1           1         2   user2     pass2   설현      서울      코트   150000    버버리
2           2         3   user3     pass3   원빈      대전     반바지    30000   유니클로
3           3         4   user4     pass4  송혜교      대구     스커트    55000     자라
4           4         5   user5     pass5  소지섭      부산      코트  1100000   알레그리
5           5         6   user6     pass6  김지원      울산     티셔츠     9900   지오다노
6           6         7   user6     pass6  김지원      울산     운동화   220000     텐디
7           7         8   user1     pass1  손흥민      런던     스커트    30000  크로커다일
8           8         9   user1     pass1  손흥민      런던      코트   580000    띠어리
  user_id name  count
0   user1  손흥민      3
5   user6  김지원      2
1   user2   설현      1
2   user3   원빈      1
3   user4  송혜교      1
4   user5  소지섭      1
229900
